mySite/myContent/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^demo/$', views.demo, name='demo'),
    url(r'^jcdb_logout/$', views.jcdb_logout, name='jcdb_logout'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^instructions/$', views.instructions, name='instructions'),
]

mySite/mySite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')), # for description, see: https://docs.djangoproject.com/en/1.8/topics/auth/default/#using-the-views for description of django.contrib.auth.urls
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('myContent.urls', namespace='myContent')),
    url(r'^Uploader/', include('Uploader.urls', namespace='Uploader')),
    url(r'^pdfjs/', include('pdfjs.urls', namespace='pdfjs')),
    url(r'^Groups/', include('Groups.urls', namespace='Groups')),
    url(r'^UserProfiles/', include('UserProfiles.urls', namespace='UserProfiles')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # TODO: disable this in production


# -*- coding: utf-8 -*-
#from django.conf.urls import patterns, include, url
#from django.conf import settings
#from django.conf.urls.static import static

mySite/pdfjs/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^viewer/(?P<document_pk>[0-9]+)/$', views.viewer, name='viewer'),
    url(r'^viewer_pdf/(?P<document_pk>[0-9]+)/$', views.viewer_pdf, name='viewer_pdf'),
    url(r'^viewer_notes/(?P<document_pk>[0-9]+)/$', views.viewer_notes, name='viewer_notes'),
    url(r'^addNote/$', views.addNote, name='addNote'),
    url(r'^replyNote/$', views.replyNote, name='replyNote'),
    url(r'^editNotetext/$', views.editNotetext, name='editNotetext'),
    url(r'^deleteNotetext/$', views.deleteNotetext, name='deleteNotetext'),
    url(r'^resizeNote/$', views.resizeNote, name='resizeNote'),
    url(r'^dragNote/$', views.dragNote, name='dragNote'),
]

mySite/myContent/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from pdfjs.views import viewer

def index(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('Groups:index'))
    else:
        context = {}
        return render(request, 'myContent/index.html', context)

def demo(request):
    logout(request)
    user = authenticate(username="guest", password="guestguest")
    login(request, user)
    return viewer(request,1)

def jcdb_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('myContent:index'))

def faq(request):
    if request.user.pk==2: # guest
        logout(request)
        return HttpResponseRedirect(reverse('Groups:index'))
    else:
        context = {}
        return render(request, 'myContent/faq.html', context)

def instructions(request):
    context = {}
    return render(request, 'myContent/instructions.html', context)

mySite/myContent/templates/myContent/faq.html
{% extends "MCBase/base.html" %}
{% load staticfiles %}

{% block javascript %}
  <link rel="stylesheet" href="{% static 'myContent/css/faq.css' %}">
{% endblock %}

{% block title %}
  jcdb
{% endblock %}

{% block body_block %}

  <div class="box">

  <h1>Frequently asked questions</h1>
  <div class="vertical-spacer"></div>

    <div class="small-box color-blue">
      What is JournalClubDB?
    </div>
    <div class="small-box">
      JournalClubDB is an online forum where you can upload and discuss scientific articles
      <br /> <br />
      JournalClubDB is NOT a long term storage solution for your papers. We may delete your old papers (uploaded >3 months ago)
      if we run out of server space.
    </div>

    <div class="vertical-spacer"></div>

    <div class="small-box color-blue">
      When I log in with social media, google/facebook/twitter tells me that JournalClubDB
      can view my email address, etc. What are you doing with my information?
    </div>
    <div class="small-box">
      JournalClubDB is committed to protecting your privacy, and we do absolutely
      nothing with your information. We selected the most minimally intrusive settings
      when setting up social authentication with google/facebook/twitter.
    </div>

    <div class="vertical-spacer"></div>

    <div class="small-box color-blue">
      What are the rules at JCDB?
    </div>
    <div class="small-box">
      Don't do anything illegal. This includes obeying copyright law. Note the articles you
      upload can only be read by your group so you should be covered by Fair Use laws as long
      as you do not broadcast your secret key to the whole world.
    </div>

    <div class="vertical-spacer"></div>

    <div class="small-box color-blue">
      Where can I get instructions on how to use JournalClubDB?
    </div>
    <div class="small-box">
      Click <a href="{% url 'myContent:instructions' %}">here</a>.
    </div>

    <div class="vertical-spacer"></div>

    <div class="small-box color-blue">
      How can I get in contact with the developers?
    </div>
    <div class="small-box">
      Click <a href="http://www.michael-chiang.com/contact/">here</a>. We're pretty responsive to emails.
    </div>

    <div class="vertical-spacer"></div>

    <div class="small-box color-blue">
      Will JournalClubDB become pay-to-use in the future?
    </div>
    <div class="small-box">
      JCDB is free-to-use and it will remain free.
    </div>

    <div class="vertical-spacer"></div>

    <div class="small-box color-blue">
      Who can access the articles that I upload?
    </div>
    <div class="small-box">
      JCDB is designed so that only people who you invite into your group can
      see the articles you upload. Full disclosure, JCDB is not hardened against
      attack; please do not upload your top-secret Benghazi emails to our servers.
    </div>

    <div class="vertical-spacer"></div>

    <div class="small-box color-blue">
      Do you have any legal disclaimers?
    </div>
    <div class="small-box">
      This service is provided as is and JournalClubDB disclaims all warranties
      with regard to this service, including all implied warranties of merchantability
      and fitness. In no event shall JournalClubDB be liable for any special, direct,
      indirect, or consequetial damages or any damages whatsoever resulting from loss
      of use, data or profits, whether in action of contract, negligence or tortious
      action, arising out of or in connetion with the use or performance of this service.
    </div>

  </div>

{% endblock %}

mySite/myContent/templates/myContent/index.html
{% extends "MCBase/base-extended.html" %}
{% load staticfiles %}

{% block javascript %}
  <link rel="stylesheet" href="{% static 'myContent/css/index.css' %}">
{% endblock %}

{% block title %}
  jcdb
{% endblock %}

{% block body_block %}
  <!--
  This file is modified from: http://blackrockdigital.github.io/startbootstrap-landing-page/
  under the terms of the MIT license. License is include below
  The MIT License (MIT)
  Copyright (c) 2013-2016 Blackrock Digital LLC.
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  -->
  <div class="intro-header full-page">
        <div class="container full-page">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>journalClubDB</h1>
                        <h3>a free service for collaborative pdf annotation</h3>
                        <hr class="intro-divider">
                        <h5>Log in with social media to get started</h3>
                        <ul class="list-inline intro-social-buttons">
                            <li>
                                <a href="{% url 'social:begin' backend='google-oauth2' %}" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">google</span></a>
                            </li>
		 	    <!--
                            <li>
                                <a href="{% url 'social:begin' backend='facebook' %}" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">facebook</span></a>
                            </li>
                            <li>
                                <a href="{% url 'social:begin' backend='twitter' %}" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">twitter</span></a>
                            </li>
			   -->
                        </ul>
                        <hr class="intro-divider">
                        <h5>Or try out the demo</h5>
                        <a href="{% url 'myContent:demo' %}" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">demo</span></a>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>

    <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="list-inline center">
                            <li class="footer-menu-divider">⋅</li>
                            <li>
                                <a href="http://www.michael-chiang.com/contact/">Contact</a>
                            </li>
                            <li class="footer-menu-divider">⋅</li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>

{% endblock %}

mySite/myContent/templates/myContent/instructions.html
{% extends "MCBase/base.html" %}
{% load staticfiles %}

{% block javascript %}
  <link rel="stylesheet" href="{% static 'myContent/css/faq.css' %}">
  <link rel="stylesheet" href="{% static 'myContent/css/instructions.css' %}">
{% endblock %}

{% block title %}
  jcdb
{% endblock %}

{% block body_block %}

  <div class="box content">

    <h1><strong>journalClubDB</strong>: instructions for use</h1>
    <p>JournalClubDB (<a href="http://www.journalClubDB.com">jcdb</a>) is a website where users can collaboratively annotate pdfs. This&nbsp;blog post contains instructions on how to use the site. JCDB should work on Chrome, Safari, and IE10 but I suggest you use Chrome.</p>
  </div>

    <div class="box">
      <h2><strong>Logging in</strong></h2>

      <p>You log into jcdb via social media. On the <a href="http://www.journalClubDB.com/jcdb_logout/">landing page</a>, you will see three buttons.</p>

      <div style="text-align:center">
      <figure class="image" style="display:inline-block"><a href="http://www.michael-chiang.com/media/jcdb_login.jpg"><img alt="" height="103" src="http://www.michael-chiang.com/media/jcdb_login.jpg" width="150"></a>
      <figcaption><strong>Figure 1: Log in with social media (red arrow)</strong></figcaption>
      </figure>
      </div>

      <p>Click on one of these three buttons to log in with Google, Facebook, or Twitter respectively. You can give yourself an alias later if you don't like your google/facebook/twitter name. If you are already logged into Google/Twitter/Facebook, you may be logged in automatically; in this case, skip this step and proceed directly to the next section <strong>Create a Group</strong>.</p>
    </div>

    <div class="box">

      <h2><strong>Create a group</strong></h2>

      <p>After you log in, you will be redirected to your Home page (see Figure 2). On your Home page, you will be able to create groups. Once you create a group, you will be able to upload pdfs for collaborative annotation and invite other members.</p>

      <div style="text-align:center">
      <figure class="image" style="display:inline-block"><a href="/media/jcdb_home.jpg "><img alt="" height="150" src="/media/jcdb_home.jpg " width="271"></a>
      <figcaption><strong>Figure 2: Create a new group on your Home page (red arrow). You can get back to your home page at any time by clicking "Home" (green arrow).</strong></figcaption>
      </figure>
      </div>

      <div style="text-align:center">
      <figure class="image" style="display:inline-block"><a href="/media/jcdb_createGroup.jpg"><img alt="" height="150" src="/media/jcdb_createGroup.jpg" width="271"></a>
      <figcaption><strong>Figure 3: Type in a name and secret key</strong></figcaption>
      </figure>
      </div>

      <p>To create a group, click on "Create a new group" (Figure 2). You will see the Create Group screen pop up (Figure 3).&nbsp;Type in a name for your group, as well as a "secret key". This secret key will be used by other people to join your group. Needless to say, you should NOT use a sensitive password (like your bank account or email password) as your secret key. Don't worry about remembering your secret key; you will be able to retrieve it later. Note that you can create and join multiple groups if you participate in&nbsp;multiple journal clubs.</p>
    </div>


    <div class="box">

      <h2><strong>Upload a paper</strong></h2>

      <p>Once you create a group, you should be redirected to your Group page (Figure 4). On your group page, you will be able to upload papers (Figure 4, red arrow).</p>

      <div style="text-align:center">
      <figure class="image" style="display:inline-block"><a href="/media/jcdb_group.jpg"><img alt="" height="150" src="/media/jcdb_group.jpg" width="324"></a>
      <figcaption><strong>Figure 4: Upload a paper (red arrow) or administrate your group (green arrow). As always, you can go back to your home page by clicking "Home" (blue arrow).</strong></figcaption>
      </figure>
      </div>

      <p>If you on the "add new paper" button, you will be shown the Upload Paper interface (Figure 5). Go ahead and upload a pdf.</p>

      <div style="text-align:center">
      <figure class="image" style="display:inline-block"><a href="/media/jcdb_uploadpdf.jpg"><img alt="" height="141" src="/media/jcdb_uploadpdf.jpg" width="450"></a>
      <figcaption><strong>Figure 5: Upload a pdf</strong></figcaption>
      </figure>
      </div>

      <p>After you upload a pdf, you will be redirected back to the Group page. You should see the PDF you uploaded (Figure 6). If you want to change the pdf name to something easier to remember, go look at the options in&nbsp;"Moderator Tools". You can also notify other group members that you uploaded a new paper in moderator tools.</p>

      <div style="text-align:center">
      <figure class="image" style="display:inline-block"><a href="/media/jcdb_newpaper.jpg"><img alt="" height="150" src="/media/jcdb_newpaper.jpg" width="370"></a>
      <figcaption><strong>Figure 6: Click on the paper you uploaded (red arrow) to begin annotation.</strong></figcaption>
      </figure>
      </div>
    </div>

    <div class="box">

      <h2><strong>Annotate your paper</strong></h2>

      <p>Click on the paper you want to annotate on your Group page (see Figure 6). You should be redirected to the annotation interface (Figure 7).</p>

      <div style="text-align:center">
      <figure class="image" style="display:inline-block"><a href="/media/jcdb_annotate.jpg"><img alt="" height="278" src="/media/jcdb_annotate.jpg" width="400"></a>
      <figcaption><strong>Figure 7: Double click to create a new note</strong></figcaption>
      </figure>
      </div>

      <p>In the annotation interface, double click anywhere to create a new note. You can reply to existing notes on the right panel, by clicking the "reply" button (red arrow). You can see which notes correspond to which replies by clicking the "zoom" buttons (blue and green arrows, respectively).</p>
    </div>


    <div class="box">
      <h2><strong>Invite other users to your group</strong></h2>

      <p>Go to the group page and click on "Administration&nbsp;Tools" (See <a href="/media/jcdb_group.jpg">Figure 4</a>, green arrow). You will be brought to the Group Administration Page (Figure 8).</p>

      <div style="text-align:center">
      <figure class="image" style="display:inline-block"><a href="/media/jcdb_invite.jpg"><img alt="" height="150" src="/media/jcdb_invite.jpg" width="253"></a>
      <figcaption><strong>Figure 8</strong></figcaption>
      </figure>
      </div>

      <p>Here, you will see a message (red box, Figure 8) that contains a link and secret key that users an use to join your group. Copy-paste and email this message to people you want to join your group.</p>
    </div>

    <div class="box">

      <h2><strong>Conclusion</strong></h2>

      <p>You should now be able to:</p>

      <ol>
      	<li>Log into JCDB</li>
      	<li>Create a group</li>
      	<li>Upload a paper</li>
      	<li>Annotate the paper</li>
      	<li>Invite members into your group</li>
      </ol>

      <p>Hopefully, that should be enough to get you started. If you have questions, feel free to <a href="http://www.michael-chiang.com/contact/">email</a> me. Good luck!</p>
    </div>



{% endblock %}