mySite/mySite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')), # for description, see: https://docs.djangoproject.com/en/1.8/topics/auth/default/#using-the-views for description of django.contrib.auth.urls
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('myContent.urls', namespace='myContent')),
    url(r'^Uploader/', include('Uploader.urls', namespace='Uploader')),
    url(r'^pdfjs/', include('pdfjs.urls', namespace='pdfjs')),
    url(r'^Groups/', include('Groups.urls', namespace='Groups')),
    url(r'^UserProfiles/', include('UserProfiles.urls', namespace='UserProfiles')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # TODO: disable this in production


# -*- coding: utf-8 -*-
#from django.conf.urls import patterns, include, url
#from django.conf import settings
#from django.conf.urls.static import static

mySite/pdfjs/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^viewer/(?P<document_pk>[0-9]+)/$', views.viewer, name='viewer'),
    url(r'^viewer_pdf/(?P<document_pk>[0-9]+)/$', views.viewer_pdf, name='viewer_pdf'),
    url(r'^viewer_notes/(?P<document_pk>[0-9]+)/$', views.viewer_notes, name='viewer_notes'),
    url(r'^addNote/$', views.addNote, name='addNote'),
    url(r'^replyNote/$', views.replyNote, name='replyNote'),
    url(r'^editNotetext/$', views.editNotetext, name='editNotetext'),
    url(r'^deleteNotetext/$', views.deleteNotetext, name='deleteNotetext'),
    url(r'^resizeNote/$', views.resizeNote, name='resizeNote'),
    url(r'^dragNote/$', views.dragNote, name='dragNote'),
]

mySite/pdfjs/models.py
from django.db import models
from django.contrib.auth.models import User
from Uploader.models import Document
from UserProfiles.models import UserProfile

class Note(models.Model):
    user = models.ForeignKey(User)
    time = models.DateTimeField(auto_now_add=True)
    document = models.ForeignKey(Document)
    page_number = models.PositiveIntegerField()
    x_normalized_position = models.FloatField()
    y_normalized_position = models.FloatField()
    width_normalized = models.FloatField()
    height_normalized = models.FloatField()

    class Meta:
        ordering = ['page_number', 'y_normalized_position']

    def __str__(self):
        return str(self.pk)
    def addText(self,user,text):
        self.save()
        noteText = NoteText(user=user,text=text,note=self)
        noteText.save()
        return noteText

    # get all notes in a given document. return as json object
    def getNotesJson(document_pk):
        document = Document.objects.get(pk=document_pk)
        notes = Note.objects.filter(document=document)
        json_obj = []
        for note in notes:
            obj = Note.getNoteJson(note)
            json_obj.append(obj)
        return json_obj
    def getNoteJson(note):
        notetexts = note.notetext_set.all() # TODO: sort by time
        note_text = []
        for notetext in notetexts:
            obj2 = NoteText.getNotetextJson(notetext)
            note_text.append(obj2)
        obj =   {'pk':note.pk,
                'page_number':note.page_number,
                'x_normalized_position':note.x_normalized_position,
                'y_normalized_position':note.y_normalized_position,
                'width_normalized':note.width_normalized,
                'height_normalized':note.height_normalized,
                'note_text':note_text,
                }
        return obj

class NoteText(models.Model):
    user = models.ForeignKey(User)
    time = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    note = models.ForeignKey(Note)
    def __str__(self):
        return self.text
    def getNotetextJson(notetext):
        obj = {'username':notetext.user.userprofile.getName(),
                'time':notetext.time.strftime('%m-%d-%Y'), # TODO: switch to age
                'text':notetext.text,
                'pk':notetext.pk,
                }
        return obj
    def editText(self,text):
        self.text=text;
        self.save();
    # returns True if notetext object if first in Note
    def isFirst(self):
        note = self.note
        notetexts = note.notetext_set.order_by('time')
        first_pk = notetexts[0].pk
        if first_pk == self.pk:
            return True
        else:
            return False

mySite/pdfjs/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from Uploader.models import Document
from django.conf import settings
from django.http import JsonResponse
from .models import *
from django.core.urlresolvers import reverse
from django.views.decorators.cache import never_cache

def index(request):
    notes = Note.objects.all()
    noteTexts = NoteText.objects.all()
    context = {'notes':notes,'noteTexts':noteTexts}
    return render(request, 'pdfjs/index.html', context)

@never_cache
def viewer(request,document_pk):
    document = Document.objects.get(pk=document_pk)
    group = document.group
    if group.members.filter(pk=request.user.pk).exists() or request.user.is_superuser:
        context = {'document_pk':document_pk}
        return render(request, 'pdfjs/viewer_iframe.html', context)
    else:
        return HttpResponseRedirect(reverse('myContent:index'))

# View for rendering pdf in iframe #1
@never_cache
def viewer_pdf(request,document_pk):
    document = Document.objects.get(pk=document_pk)
    group = document.group
    if group.members.filter(pk=request.user.pk).exists() or request.user.is_superuser:
        pdf_url = settings.MEDIA_URL + document.docfile.name
        addnote_url = reverse('pdfjs:addNote')
        dragnote_url = reverse('pdfjs:dragNote')
        resizenote_url = reverse('pdfjs:resizeNote')
        notes_json = Note.getNotesJson(document_pk)
        context = {'pdf_url':pdf_url,'addnote_url':addnote_url,'dragnote_url':dragnote_url,'resizenote_url':resizenote_url,'notes_json':notes_json,'document_pk':document_pk}
        return render(request, 'pdfjs/viewer_pdf.html', context)
    else:
        return HttpResponseRedirect(reverse('myContent:index'))

# View for rendering notes in iframe #2
@never_cache
def viewer_notes(request,document_pk):
    document = Document.objects.get(pk=document_pk)
    group = document.group
    if group.members.filter(pk=request.user.pk).exists() or request.user.is_superuser:
        notes = Note.objects.filter(document=document)
        url_deletenotetext = reverse('pdfjs:deleteNotetext');
        url_editNotetext = reverse('pdfjs:editNotetext')
        url_replynote = reverse('pdfjs:replyNote')
        context = {'document_pk':document_pk,"notes":notes,"url_deletenotetext":url_deletenotetext,'url_editNotetext':url_editNotetext,'url_replynote':url_replynote}
        return render(request, 'pdfjs/viewer_notes.html', context)
    else:
        return HttpResponseRedirect(reverse('myContent:index'))

def replyNote(request):
    if request.method == 'POST':
        note_pk = request.POST.get("note_pk")
        form_text = request.POST.get("form_text")
        user = request.user
    else:
        return HttpResponse("Attempted to reply note without POST")
    note = Note.objects.get(pk=note_pk)
    group = note.document.group
    if not group.members.filter(pk=request.user.pk).exists() and not request.user.is_superuser:
        return HttpResponse("You are trying to reply to a note in a group you do not belong to")
    note = Note.objects.get(pk=note_pk)
    notetext = note.addText(user=user,text=form_text)
    notetext_obj = NoteText.getNotetextJson(notetext)
    response = {'notetext_obj':notetext_obj,'note_pk':note.pk}
    return JsonResponse(response)

# return json object representing the note added
def addNote(request):
    if request.method == 'POST':
        document_pk = request.POST.get("document_pk")
        form_text = request.POST.get("form_text")
        user = request.user
        page_number = request.POST.get("page_number")
        x_normalized = request.POST.get("x_normalized")
        y_normalized = request.POST.get("y_normalized")
        width_normalized = request.POST.get("width_normalized")
        height_normalized = request.POST.get("height_normalized")
        document = Document.objects.get(pk=document_pk)
        group = document.group
    else:
        return HttpResponse("Attempted to add note without POST")
    if not group.members.filter(pk=request.user.pk).exists() and not request.user.is_superuser:
        return HttpResponse("You are trying to add a note in a group you do not belong to")
    note = Note(user=user,
                document=Document.objects.get(pk=document_pk),
                page_number=page_number,
                x_normalized_position=x_normalized,
                y_normalized_position=y_normalized,
                width_normalized=width_normalized,
                height_normalized=height_normalized,)
    note.save()
    note.addText(user=user,text=form_text)
    note_obj = Note.getNoteJson(note)
    response = {'note_obj':note_obj}
    return JsonResponse(response)

def editNotetext(request):
    if request.method == 'POST':
        notetext_pk = request.POST.get("notetext_pk")
        form_text = request.POST.get("form_text")
        user = request.user
    else:
        return HttpResponse("Attempted to reply note without POST")
    notetext = NoteText.objects.get(pk=notetext_pk)
    group = notetext.note.document.group
    if not group.moderators.filter(pk=request.user.pk).exists() and not notetext.user == request.user and not request.user.is_superuser:
        return HttpResponse("You are trying to edit a note and you are not a moderator / note owner")
    notetext.editText(text=form_text)
    note_pk = notetext.note.pk
    isFirst = notetext.isFirst()
    response = {'isFirst':isFirst,'form_text':form_text,'pk':notetext_pk,'note_pk':note_pk}
    return JsonResponse(response)

def deleteNotetext(request):
    if request.method == 'POST':
        notetext_pk = request.POST.get("notetext_pk")
    else:
        return HttpResponse("Attempted to reply note without POST")
    notetext = NoteText.objects.get(pk=notetext_pk)
    group = notetext.note.document.group
    if not group.moderators.filter(pk=request.user.pk).exists() and not notetext.user == request.user and not request.user.is_superuser:
        return HttpResponse("You are trying to edit a note and you are not a moderator / note owner")
    # Remove entier note if notetext is first
    isFirst = notetext.isFirst()
    if isFirst:
        note = notetext.note
        note.delete()
    else:
        notetext.delete()
    response = {'delete_entire_note':isFirst}
    return JsonResponse(response)

def resizeNote(request):
    if request.method == 'POST':
        width_normalized = request.POST.get("width_normalized")
        height_normalized = request.POST.get("height_normalized")
        note_pk = request.POST.get("note_pk")
    else:
        return HttpResponse("Attempted to resize note without POST")
    note = Note.objects.get(pk=note_pk)
    group = note.document.group
    if not group.members.filter(pk=request.user.pk).exists() and not request.user.is_superuser:
        return HttpResponse("You are trying to resize a note in a group you do not belong to")
    note.width_normalized = width_normalized
    note.height_normalized = height_normalized
    note.save()
    response = {}
    return JsonResponse(response)

def dragNote(request):
    if request.method == 'POST':
        x_normalized = request.POST.get("x_normalized")
        y_normalized = request.POST.get("y_normalized")
        note_pk = request.POST.get("note_pk")
    else:
        return HttpResponse("Attempted to resize note without POST")
    note = Note.objects.get(pk=note_pk)
    group = note.document.group
    if not group.members.filter(pk=request.user.pk).exists() and not request.user.is_superuser:
        return HttpResponse("You are trying to resize a note in a group you do not belong to")
    note.x_normalized_position = x_normalized
    note.y_normalized_position = y_normalized
    note.save()
    response = {}
    return JsonResponse(response)

mySite/pdfjs/templates/pdfjs/index.html
{% extends "MCBase/base.html" %}
{% load staticfiles %}

{% block javascript %}
  <link rel="stylesheet" href="{% static 'pdfjs/css/viewer_pdf.css' %}">
  <script type="text/javascript" src="{% static 'pdfjs/js/index.js' %}"></script>
  <script type="text/javascript" src="{% static 'pdfjs/js/iframe.js' %}"></script>

{% endblock %}

{% block title %}
{% endblock %}



{% block body_block %}
Example note: <br /> <br />

<div class="note">
  Type here:
<form role="form" action="{% url 'pdfjs:addNote' %}" method=POST>
  {% csrf_token %}
  <input type="hidden" name="document_pk" value="2" />
  <input type="hidden" name="page_number" value="1" />
  <input type="hidden" name="x_normalized" value="3" />
  <input type="hidden" name="y_normalized" value="4" />
  <input type="hidden" name="width" value="3" />
  <input type="hidden" name="height" value="4" />
  <textarea name="form_text" cols="10" rows="5"></textarea>
</form>
<button class="submit-previous-form">submit</button>
</div>


<br /><br /><br />
<br /><br /><br />
<br /><br /><br />

<div>
  Notes:
  {% for note in notes %}
    {{ note }}
  {% endfor %}
</div>

<div>
  note texts:
  {% for noteText in noteTexts %}
    {{ noteText }}
  {% endfor %}
</div>


{% endblock %}

mySite/pdfjs/templates/pdfjs/viewer_iframe.html
{% extends "MCBase/base-extended.html" %}
{% load staticfiles %}

{% block javascript %}
  <link rel="stylesheet" href="{% static 'pdfjs/css/viewer_iframe.css' %}">
  <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
  <meta http-equiv="Pragma" content="no-cache" />
  <meta http-equiv="Expires" content="0" />
{% endblock %}

{% block title %}
  jcdb
{% endblock %}



{% block body_block %}
<table>

<!-- trigger events across iframes -->
<!-- http://stackoverflow.com/questions/7228708/trigger-from-iframe-to-sibling-iframe -->
<!-- http://stackoverflow.com/questions/6697364/triggering-a-jquery-event-from-iframe -->

<script>
  var random_number = new Date().getTime()

  document.write('<div class="box1"> \
      <iframe style="height: 90%; width: 100%" src="{% url "pdfjs:viewer_pdf" document_pk %}?'+random_number+'"> \
      </iframe> \
  </div> \
  <div class="box2"> \
      <iframe id="iframe2" style="height: 90%; width: 100%" src="{% url "pdfjs:viewer_notes" document_pk %}?'+random_number+'"> \
      </iframe></td> \
  </div>');

</script>



{% endblock %}

mySite/pdfjs/templates/pdfjs/viewer_notes.html
{% load staticfiles %}
{% load MCBase_templatetags %}

<html>

  <head>

    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />

    <script src="{% static 'MCBase/js/jquery-2.1.4.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'pdfjs/css/viewer_notes.css' %}"/>
    <script src="{% static 'pdfjs/js/viewer_notes.js' %}"></script>
    <script>
      url_deletenotetext = "{{ url_deletenotetext }}"
      csrf_token = "{{ csrf_token }}"
      url_editNotetext = "{{url_editNotetext}}"
      url_replynote = "{{url_replynote}}"
    </script>
  </head>


  <body>
    {% for note in notes %}
      <!-- if you modify, you should also change appendNote() in viewer_notes.js -->
      <div pagenumber="{{ note.page_number }}" id="note{{note.pk}}" class="note">
        <div id="replybox{{note.pk}}">
        {% for notetext in note.notetext_set.all %}
          {% if forloop.counter == 1 %}
            <div id="notetext{{notetext.pk}}">
          {% else %}
            <div id="notetext{{notetext.pk}}" class="not-first-post">
          {% endif %}

          <div id="notetextonly{{notetext.pk}}">
            {{ notetext.text }}
          </div>
          <div class="signature left">
            --{{ notetext.user.userprofile.getName }}, {{ notetext.time|age }}
          </div>
          {% if request.user.pk == notetext.user.pk %}
            <div class="right signature edit_button">
              <a notepk="{{note.pk}}" pk="{{notetext.pk}}" class="delete-link">delete</a>
              <a pk="{{notetext.pk}}" class="edit-link">edit</a>
            </div>
            <div id="editform{{notetext.pk}}" class="hidden">
              <form class="note-form" role="form" action="{% url 'pdfjs:editNotetext' %}" method=POST>
                {% csrf_token %}
                <input type="hidden" name="notetext_pk" value="{{ notetext.pk }}" />
                    <textarea name="form_text" cols="10" rows="5">{{ notetext.text }}</textarea>
              </form>
              <button class="edit-button">submit edit</button>
            </div>
          {% endif %}
          <div style="clear: both;"></div>
          </div>
        {% endfor %}
        </div>
        <div id="replyfooter{{note.pk}}">
          <a notepk="{{note.pk}}" class="note_footer zoom left">zoom</a>
          <a pk="{{note.pk}}" class="note_footer reply-link right">reply</a>
        </div>
        <div style="clear: both;"></div>
        <div id="replyform{{note.pk}}" class="hidden replyform">
          <form class="note-form" role="form" action="{% url 'pdfjs:replyNote' %}" method=POST>
            {% csrf_token %}
            <input type="hidden" name="note_pk" value="{{ note.pk }}" />
            <textarea id="textarea{{note.pk}}" name="form_text" cols="10" rows="5"></textarea>
          </form>
          <button class="reply-button">submit</button>
        </div>
      </div>
    {% endfor %}
  </body>
</html>