mySite/UserProfiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^new_user/$', views.new_user, name='new_user'),
    url(r'^deleteNotification/(?P<notification_pk>[0-9]+)/$', views.deleteNotification, name='deleteNotification'),
    url(r'^editProfileInterface/$', views.editProfileInterface, name='editProfileInterface'),
    url(r'^editAlias/$', views.editAlias, name='editAlias'),
]

mySite/mySite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')), # for description, see: https://docs.djangoproject.com/en/1.8/topics/auth/default/#using-the-views for description of django.contrib.auth.urls
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('myContent.urls', namespace='myContent')),
    url(r'^Uploader/', include('Uploader.urls', namespace='Uploader')),
    url(r'^pdfjs/', include('pdfjs.urls', namespace='pdfjs')),
    url(r'^Groups/', include('Groups.urls', namespace='Groups')),
    url(r'^UserProfiles/', include('UserProfiles.urls', namespace='UserProfiles')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # TODO: disable this in production


# -*- coding: utf-8 -*-
#from django.conf.urls import patterns, include, url
#from django.conf import settings
#from django.conf.urls.static import static

mySite/pdfjs/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^viewer/(?P<document_pk>[0-9]+)/$', views.viewer, name='viewer'),
    url(r'^viewer_pdf/(?P<document_pk>[0-9]+)/$', views.viewer_pdf, name='viewer_pdf'),
    url(r'^viewer_notes/(?P<document_pk>[0-9]+)/$', views.viewer_notes, name='viewer_notes'),
    url(r'^addNote/$', views.addNote, name='addNote'),
    url(r'^replyNote/$', views.replyNote, name='replyNote'),
    url(r'^editNotetext/$', views.editNotetext, name='editNotetext'),
    url(r'^deleteNotetext/$', views.deleteNotetext, name='deleteNotetext'),
    url(r'^resizeNote/$', views.resizeNote, name='resizeNote'),
    url(r'^dragNote/$', views.dragNote, name='dragNote'),
]

mySite/MCBase/views.py
from django.shortcuts import render
import json
from bson import json_util

def serialize_json(json_dict):
    return json.dumps(json_dict, default=json_util.default)

def deserialize_json_string(str):
    return json.loads(str, object_hook=json_util.object_hook)

mySite/MCBase/templates/MCBase/base-extended.html
<!-- This file contains the base django template used for all webpages -->
<!-- use with: extends "base.html"  -->


<html>
  <head>
    {% load staticfiles %}
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="{% static 'MCBase/js/jquery-2.1.4.min.js' %}"></script>
    <script src="{% static 'MCBase/js/jquery-ui-1.11.4.custom/jquery-ui.js' %}"></script>
    <link rel="stylesheet" href="{% static 'MCBase/js/jquery-ui-1.11.4.custom/jquery-ui.css' %}">
    <script src="{% static 'MCBase/bootstrap-3.3.5-dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'MCBase/js/base.js' %}"></script>
    <link rel="stylesheet" href="{% static 'MCBase/bootstrap-3.3.5-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'MCBase/css/base.css' %}">
    {% block javascript %}{% endblock %}
  </head>

  <body>

  <!-- navbar -->
  {% load MCBase_templatetags %}
  {% load_base_navbar %}

  <!-- authentication modal -->
  {% include "MCBase/base-socialAuthModal.html" %}

  <!-- main content -->
  <div>
    {% block body_block %}{% endblock %}
  </div>



  </body>
</html>

mySite/MCBase/templates/MCBase/base-navbar.html
<!-- this file should be included in template base.html -->
{% load staticfiles %}
{% load MCBase_templatetags %}

<link rel="stylesheet" href="{% static 'MCBase/css/base-navbar.css' %}">

<nav class="navbar navbar-default navbar-static-top full-width-navbar"> <!-- for example navbars, see: https://getbootstrap.com/examples/navbar-fixed-top/ -->
  <div class="container full-width-navbar">

      <!-- logo -->
      <div class="navbar-header navbar-font1">
        <a class="navbar-brand" href="#">{{ website_name }}</a>
      </div>

      <!-- left-side navbar -->
      <div id="navbar" class="navbar-collapse collapse">
        {% if user.is_authenticated %}
          {% for element,href in left_side_nav|zip_lists:left_side_href %}
            <ul class="nav navbar-nav">
              <li class="nav-element {% active href %}"><a href="{% url href %}">{{ element }}</a></li>
            </ul>
          {% endfor %}
        {% else %}
          {% for element,href in left_side_nav|zip_lists:left_side_href %}
            <ul class="nav navbar-nav">
              <li class="nav-element {% active href %}"><a href="{% url href %}">{{ element }}</a></li>
            </ul>
          {% endfor %}
        {% endif %}

        <!-- right-side navbar -->
        <ul class="nav navbar-nav navbar-right navbar-font1">
          {% if user.is_authenticated %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.userprofile.getName }}<span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'UserProfiles:editProfileInterface' %}">User profile</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{% url 'logout' %}?next=/">Logout</a></li>
              </ul>
            </li>

          {% else %}
            <li class="cursor-pointer"><a class="toggle-login-modal" data-toggle="modal" data-target="#social-auth-modal">Login</a></li>
          {% endif %}
        </ul>

    </div>
  </div>
</nav>

mySite/MCBase/templates/MCBase/base-socialAuthModal.html
<!-- this file should be included in template base.html -->
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'MCBase/css/base-socialAuthModal.css' %}">

<div id="social-auth-modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <div id="socialAuthModal-title" class="center-text">Use google, facebook, or twitter to log in. It only takes seconds!</div>
      </div>
      <div class="modal-body">

        <!-- login with social media -->
        <div class="row center-text">
          <a class="socialAuthModal-link" href="{% url 'social:begin' backend='google-oauth2' %}">
            <img height="150" src="{% static 'MCBase/images/google-icon.png'%}" alt="Log in with google!">
          </a>

          <a class="socialAuthModal-link" href="{% url 'social:begin' backend='facebook' %}">
            <img height="150" src="{% static 'MCBase/images/facebook-icon.png'%}" alt="Log in with facebook!">
          </a>

          <a class="socialAuthModal-link" href="{% url 'social:begin' backend='twitter' %}">
            <img height="150" src="{% static 'MCBase/images/twitter-icon.png'%}" alt="Log in with twitter!">
          </a>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

mySite/MCBase/templates/MCBase/base.html
<!-- This file contains the base django template used for all webpages -->
<!-- use with: extends "base.html"  -->


<html>
  <head>
    {% load staticfiles %}
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="{% static 'MCBase/js/jquery-2.1.4.min.js' %}"></script>
    <script src="{% static 'MCBase/js/jquery-ui-1.11.4.custom/jquery-ui.js' %}"></script>
    <link rel="stylesheet" href="{% static 'MCBase/js/jquery-ui-1.11.4.custom/jquery-ui.css' %}">
    <script src="{% static 'MCBase/bootstrap-3.3.5-dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'MCBase/js/base.js' %}"></script>
    <link rel="stylesheet" href="{% static 'MCBase/bootstrap-3.3.5-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'MCBase/css/base.css' %}">
    {% block javascript %}{% endblock %}
  </head>

  <body>

  <!-- navbar -->
  {% load MCBase_templatetags %}
  {% load_base_navbar %}

  <!-- authentication modal -->
  {% include "MCBase/base-socialAuthModal.html" %}

  <!-- main content -->
  <div class="container">
    {% block body_block %}{% endblock %}
  </div>



  </body>
</html>