mySite/Groups/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^addGroupInterface/$', views.addGroupInterface, name='addGroupInterface'),
    url(r'^addGroup/$', views.addGroup, name='addGroup'),
    url(r'^deleteGroup/(?P<group_pk>[0-9]+)/$', views.deleteGroup, name='deleteGroup'),
    url(r'^groupAdminPanel/(?P<group_pk>[0-9]+)/$', views.groupAdminPanel, name='groupAdminPanel'),
    url(r'^documentAdminPanel/(?P<document_pk>[0-9]+)/$', views.documentAdminPanel, name='documentAdminPanel'),
    url(r'^groupMemberView/(?P<group_pk>[0-9]+)/$', views.groupMemberView, name='groupMemberView'),
    url(r'^deleteGroup/(?P<group_pk>[0-9]+)/$', views.deleteGroup, name='deleteGroup'),
    url(r'^joinGroupInterface/(?P<group_pk>[0-9]+)/$', views.joinGroupInterface, name='joinGroupInterface'),
    url(r'^joinGroup/(?P<group_pk>[0-9]+)/$', views.joinGroup, name='joinGroup'),
    url(r'^index/$', views.index, name='index'),
    url(r'^changePermissions/(?P<user_pk>[0-9]+)/(?P<group_pk>[0-9]+)/$', views.changePermissions, name='changePermissions'),
    url(r'^changeGroupName/(?P<group_pk>[0-9]+)/$', views.changeGroupName, name='changeGroupName'),
    url(r'^changeGroupDescription/(?P<group_pk>[0-9]+)/$', views.changeGroupDescription, name='changeGroupDescription'),
    url(r'^changeGroupPassword/(?P<group_pk>[0-9]+)/$', views.changeGroupPassword, name='changeGroupPassword'),
    url(r'^changeAcceptingNewMembers/(?P<group_pk>[0-9]+)/$', views.changeAcceptingNewMembers, name='changeAcceptingNewMembers'),
    url(r'^changeUploadApprovalRequired/(?P<group_pk>[0-9]+)/$', views.changeUploadApprovalRequired, name='changeUploadApprovalRequired'),

    url(r'^deleteDocument/(?P<document_pk>[0-9]+)/$', views.deleteDocument, name='deleteDocument'),
    url(r'^sendNotification/(?P<group_pk>[0-9]+)/$', views.sendNotification, name='sendNotification'),
    url(r'^removeSelfFromGroup/(?P<group_pk>[0-9]+)/$', views.removeSelfFromGroup, name='removeSelfFromGroup'),
]

mySite/Uploader/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^upload/$', views.upload, name='upload'),
    url(r'^uploadInterface/(?P<group_pk>[0-9]+)/$', views.uploadInterface, name='uploadInterface'),
    url(r'^editTitle/(?P<document_pk>[0-9]+)/$', views.editTitle, name='editTitle'),
]

mySite/UserProfiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^new_user/$', views.new_user, name='new_user'),
    url(r'^deleteNotification/(?P<notification_pk>[0-9]+)/$', views.deleteNotification, name='deleteNotification'),
    url(r'^editProfileInterface/$', views.editProfileInterface, name='editProfileInterface'),
    url(r'^editAlias/$', views.editAlias, name='editAlias'),
]

mySite/mySite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')), # for description, see: https://docs.djangoproject.com/en/1.8/topics/auth/default/#using-the-views for description of django.contrib.auth.urls
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('myContent.urls', namespace='myContent')),
    url(r'^Uploader/', include('Uploader.urls', namespace='Uploader')),
    url(r'^pdfjs/', include('pdfjs.urls', namespace='pdfjs')),
    url(r'^Groups/', include('Groups.urls', namespace='Groups')),
    url(r'^UserProfiles/', include('UserProfiles.urls', namespace='UserProfiles')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # TODO: disable this in production


# -*- coding: utf-8 -*-
#from django.conf.urls import patterns, include, url
#from django.conf import settings
#from django.conf.urls.static import static

mySite/pdfjs/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^viewer/(?P<document_pk>[0-9]+)/$', views.viewer, name='viewer'),
    url(r'^viewer_pdf/(?P<document_pk>[0-9]+)/$', views.viewer_pdf, name='viewer_pdf'),
    url(r'^viewer_notes/(?P<document_pk>[0-9]+)/$', views.viewer_notes, name='viewer_notes'),
    url(r'^addNote/$', views.addNote, name='addNote'),
    url(r'^replyNote/$', views.replyNote, name='replyNote'),
    url(r'^editNotetext/$', views.editNotetext, name='editNotetext'),
    url(r'^deleteNotetext/$', views.deleteNotetext, name='deleteNotetext'),
    url(r'^resizeNote/$', views.resizeNote, name='resizeNote'),
    url(r'^dragNote/$', views.dragNote, name='dragNote'),
]

mySite/Groups/models.py
from django.db import models
from django.contrib.auth.models import User

class Group(models.Model):
    name = models.TextField()
    description = models.TextField(blank=True)
    time = models.DateTimeField(auto_now_add=True)
    password = models.TextField(blank=True)
    openForNewMembers = models.BooleanField(default=True)
    uploadApprovalRequired = models.BooleanField(default=False)

    admins     = models.ManyToManyField(User, blank=True, related_name="admin_of_groups")
    moderators = models.ManyToManyField(User, blank=True, related_name="mod_of_groups")
    members    = models.ManyToManyField(User, blank=True, related_name="member_of_groups") # to access groups from User instance, user.member_of_groups.all()


    def __str__(self):
        return str(self.name)
    def get_groups_that_user_is_member_of(user):
        return user.member_of_groups.all()
    def is_moderator(self,user):
        isModerator = self.moderators.filter(pk=user.pk).exists()
        return isModerator
    def is_admin(self,user):
        isAdmin = self.admins.filter(pk=user.pk).exists()
        return isAdmin

mySite/Groups/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import *
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from Uploader.models import Document
from UserProfiles.models import *
from django.conf import settings
import os
from django.contrib.auth import logout

# If user is logged in, show group manager. Otherwise, show landing page
def index(request):
    if request.user.pk==2: # guest
        logout(request)
        return HttpResponseRedirect(reverse('Groups:index'))
    if request.user.is_authenticated():
        user = request.user
        # get groups that user is a member of
        groups = Group.get_groups_that_user_is_member_of(user)
        groups = groups.order_by('-time') # newest groups at the top
        # get papers that user can access
        documents = None
        for group in groups:
            if documents is None:
                documents = group.document_set.all()
            else:
                documents = documents | group.document_set.all()
        if documents:
            documents = documents.order_by('-time') # newest documents at the top
        # get notifications
        notifications = Notification.get(user).order_by('-time') # newest notifications at the top

        # return html
        context = {'groups':groups,'documents':documents,'notifications':notifications}
        return render(request, 'Groups/index.html', context)
    else:
        return HttpResponseRedirect(reverse('myContent:index'))

# html form for user adding a group
def addGroupInterface(request):
    if request.user.is_authenticated():
        context = {}
        return render(request, 'Groups/addGroupInterface.html', context)
    else:
        return HttpResponseRedirect(reverse('myContent:index'))

# user adds a group
def addGroup(request):
    # check for user authentication, POST
    if request.method == 'POST' and request.user.is_authenticated():
        name = request.POST.get("name")
        password = request.POST.get("password")
        user = request.user
    else:
        return HttpResponseRedirect(reverse('myContent:index'))
    # create group
    group = Group(name=name,password=password)
    group.save() # only need to save once
    group.admins.add(user)
    group.moderators.add(user)
    group.members.add(user)
    return HttpResponseRedirect(reverse('Groups:groupMemberView',args=[group.pk]))

# user removes self from group
def removeSelfFromGroup(request,group_pk):
    group = Group.objects.get(pk=group_pk)
    group.admins.remove(request.user)
    group.moderators.remove(request.user)
    group.members.remove(request.user)
    return HttpResponseRedirect(reverse('myContent:index'))

# delete a group. Only admins can delete group
def deleteGroup(request,group_pk):
    group = Group.objects.get(pk=group_pk)
    if group.admins.filter(pk=request.user.pk).exists() or request.user.is_superuser:
        group.delete()
        return HttpResponseRedirect(reverse('myContent:index'))
    else:
        return HttpResponseRedirect(reverse('myContent:index'))

# anybody can join a group if they know the password
def joinGroupInterface(request,group_pk):
    group = Group.objects.get(pk=group_pk)
    context = {'group':group,}
    return render(request,'Groups/joinGroupInterface.html',context)
# anybody can join a group if they know the password
def joinGroup(request,group_pk):
    name = request.POST.get("name")
    password = request.POST.get("password")
    user = request.user
    group = Group.objects.get(pk=group_pk)
    if not group.openForNewMembers:
        context = {'group':group,'group_closed':True}
        return render(request,'Groups/joinGroupInterface.html',context)
    elif group.password == password:
        group.members.add(user)
        return HttpResponseRedirect(reverse('Groups:groupMemberView',args=[group_pk]))
    else:
        context = {'group':group,'incorrect_password':True}
        return render(request,'Groups/joinGroupInterface.html',context)

# Make a user an admin, moderator, or member. Only admin can change permission
def changePermissions(request,user_pk,group_pk):
    # check for user authentication, POST, and make sure user is an admin of the group
    if request.method == 'POST' and request.user.is_authenticated():
        group = Group.objects.get(pk=group_pk)
        user = User.objects.get(pk=user_pk)
        permission = request.POST.get("permission")
    else:
        return HttpResponseRedirect(reverse('myContent:index'))
    if not group.admins.filter(pk=request.user.pk).exists() and not request.user.is_superuser:
        return HttpResponseRedirect(reverse('myContent:index'))
    # Change permission
    if permission == "admin":
        group.members.add(user)
        group.moderators.add(user)
        group.admins.add(user)
    elif permission == "moderator":
        group.members.add(user)
        group.moderators.add(user)
        group.admins.remove(user)
    elif permission == "member":
        group.members.add(user)
        group.moderators.remove(user)
        group.admins.remove(user)
    elif permission == "remove":
        group.members.remove(user)
        group.moderators.remove(user)
        group.admins.remove(user)
    return HttpResponseRedirect(reverse('Groups:groupAdminPanel',args=[group.pk]))

# Change name of group. Only admin can change group name
def changeGroupName(request,group_pk):
    # check for user authentication, POST, and make sure user is an admin of the group
    if request.method == 'POST' and request.user.is_authenticated():
        form_text = request.POST.get("form_text")
    else:
        return HttpResponse("Attempted to make group without authentication or POST")
    if not group.admins.filter(pk=request.user.pk).exists() and not request.user.is_superuser:
        return HttpResponseRedirect(reverse('myContent:index'))
    group = Group.objects.get(pk=group_pk)
    group.name = form_text
    group.save()
    return HttpResponseRedirect(reverse('Groups:groupAdminPanel',args=[group.pk]))

# only admin can change group description
def changeGroupDescription(request,group_pk):
    pass
# only admin can change group password
def changeGroupPassword(request,group_pk):
    # check for user authentication, POST
    if request.method == 'POST' and request.user.is_authenticated():
        form_text = request.POST.get("form_text")
    else:
        return HttpResponse("Attempted to make group without authentication or POST")
    if not group.admins.filter(pk=request.user.pk).exists() and not request.user.is_superuser:
        return HttpResponseRedirect(reverse('myContent:index'))
    group = Group.objects.get(pk=group_pk)
    group.password = form_text
    group.save()
    return HttpResponseRedirect(reverse('Groups:groupAdminPanel',args=[group.pk]))
# only admin can open and close membership
def changeAcceptingNewMembers(request,group_pk):
    # check for user authentication, POST
    if request.method == 'POST' and request.user.is_authenticated():
        membership_option = request.POST.get("membership_option")
    else:
        return HttpResponse("Attempted to make group without authentication or POST")
    group = Group.objects.get(pk=group_pk)
    if not group.admins.filter(pk=request.user.pk).exists() and not request.user.is_superuser:
        return HttpResponseRedirect(reverse('myContent:index'))
    # Change permission
    if membership_option == "open":
        group.openForNewMembers = True
        group.save()
        return HttpResponseRedirect(reverse('Groups:groupAdminPanel',args=[group_pk]))
    elif membership_option == "closed":
        group.openForNewMembers = False
        group.save()
        return HttpResponseRedirect(reverse('Groups:groupAdminPanel',args=[group_pk]))
    else:
        return HttpResponse("Invalid choice of membership_option")

# only admin can change
def changeUploadApprovalRequired(request,group_pk):
    pass

# only admins can see admin panel
def groupAdminPanel(request,group_pk):
    group = Group.objects.get(pk=group_pk)
    if not group.admins.filter(pk=request.user.pk).exists() and not request.user.is_superuser:
        return HttpResponseRedirect(reverse('myContent:index'))
    admins = group.admins.all()
    moderators = group.moderators.exclude(id__in=admins)
    members = group.members.exclude(id__in=admins).exclude(id__in=moderators)
    context = {"group":group,"admins":admins,"moderators":moderators,"members":members}
    return render(request, 'Groups/groupAdminPanel.html', context)
# only moderators and admins and original uploader can see moderator panel
def documentAdminPanel(request,document_pk):
    document = Document.objects.get(pk=document_pk)
    group = document.group
    if not group.moderators.filter(pk=request.user.pk).exists() and not request.user.is_superuser and document.user.pk != request.user.pk:
        return HttpResponseRedirect(reverse('myContent:index'))
    context = {"document":document,}
    return render(request, 'Groups/documentAdminPanel.html', context)

# only group members can see group view
def groupMemberView(request,group_pk):
    # check to make sure user is member
    group = Group.objects.get(pk=group_pk)
    if not group.members.filter(pk=request.user.pk).exists() and not request.user.is_superuser:
        return HttpResponseRedirect(reverse('myContent:index'))
    # return html
    isModerator = group.is_moderator(request.user)
    isAdmin = group.is_admin(request.user)
    documents = group.document_set.all()
    documents = documents.order_by('-time') # newest documents at the top
    context = {'group':group,'isModerator':isModerator,'isAdmin':isAdmin,'documents':documents}
    return render(request, 'Groups/groupMemberView.html', context)

# only moderators and original uploader can delete documents
def deleteDocument(request,document_pk):
    document = Document.objects.get(pk=document_pk)
    group = document.group

mySite/Groups/templates/Groups/documentAdminPanel.html
{% extends "MCBase/base.html" %}
{% load staticfiles %}

{% block javascript %}
  <link rel="stylesheet" href="{% static 'Groups/css/adminTools.css' %}">
  <script src="{% static 'Groups/js/documentAdminPanel.js' %}"></script>
{% endblock %}

{% block title %}
  admin tools
{% endblock %}



{% block body_block %}
  <h1>
    <a href="{% url 'Groups:groupMemberView' document.group.pk %}">
      Back to group
    </a>
  </h1>
  <div class=box>
    <b>Paper title:</b>
    <br />
    {{ document.getTitle }}
    <br />
    <a pk="{{document.pk}}" class="edit-link pointer">click to edit</a>
    <div class="editform" style="display: none;">
      <form class="note-form" role="form" action="{% url 'Uploader:editTitle' document.pk %}" method=POST>
        {% csrf_token %}
        <textarea name="form_text" rows="1">{{ document.getTitle }}</textarea>
        <button class="btn btn-primary" type="submit">submit edit</button>
      </form>
    </div>
  </div>

  <div class=box>
    <b>Notify the group about this paper:</b>
    <br />
    <a pk="{{document.pk}}" class="edit-link pointer">click to send notification</a>
    <div class="editform" style="display: none;">
      <form class="note-form" role="form" action="{% url 'Groups:sendNotification' document.group.pk %}" method=POST onsubmit="return getContent()">
        {% csrf_token %}
        <div id="contenteditable-notification" class="contenteditable" contenteditable="true">
          Hi all,<br />
          Check out the new paper:<br />
          <a href="{% url 'pdfjs:viewer' document.pk %}">{{ document.getTitle }}</a><br>
          --{{ request.user.userprofile.getName }}
        </div>
        <input type="hidden" name="next_url" value="{{ request.path }}" />
        <textarea id="notification-text" name="form_text" style="display:none"></textarea>
        <button class="btn btn-primary" type="submit">send notification</button>
      </form>
    </div>
  </div>

  <div class=box>
    <b>Delete paper:</b>
    <div class="red">
      Warning: this is permanent. Paper will be removed from all group members.
    </div>
    <a href="{% url 'Groups:deleteDocument' document.pk %}">Click to delete</a>
  </div>

{% endblock %}

mySite/Groups/templates/Groups/groupAdminPanel.html
{% extends "MCBase/base.html" %}
{% load staticfiles %}

{% block javascript %}
  <link rel="stylesheet" href="{% static 'Groups/css/adminTools.css' %}">
  <script src="{% static 'Groups/js/groupAdminPanel.js' %}"></script>
{% endblock %}

{% block title %}
  admin tools
{% endblock %}



{% block body_block %}
  <h1>
    <a href="{% url 'Groups:groupMemberView' group.pk %}">
      Back to group
    </a>
  </h1>

  {% if group.openForNewMembers %}
    <div class=box>
      If you want to invite more members to your group,
      copy-paste-send the the following email to them:
      <div class="small-box">
        I am inviting you to join my online journal club group <b>{{ group.name }}</b>. <br />
        To join, go to the following link:<br />
        <a href="http://{{ request.META.HTTP_HOST }}{% url 'Groups:joinGroupInterface' group.pk %}">{{ request.META.HTTP_HOST }}{% url 'Groups:joinGroupInterface' group.pk %}</a><br />
        Then, type the following secret key into the prompt:
        <span class="red"><b>{{ group.password }}</b></span><br />
        See you soon!
      </div>
    </div>
  {% else %}
    <div class=box>
      If you want to invite more members to your group,
      first open the group to new members.
    </div>
  {% endif %}


  <div class=box>
    <b>Group name:</b>
    <br />
    {{ group.name }}
    <br />
    <a pk="{{group.pk}}" class="edit-link pointer">click to edit</a>
    <div class="editform" style="display: none;">
      <form class="note-form" role="form" action="{% url 'Groups:changeGroupName' group.pk %}" method=POST>
        {% csrf_token %}
        <textarea name="form_text" rows="1">{{ group.name }}</textarea>
        <button class="btn btn-primary" type="submit">submit edit</button>
      </form>
    </div>
  </div>

  <div class=box>
    <b>Invitation secret key:</b>
    <br />
    {{ group.password }}
    <br />
    <a pk="{{group.pk}}" class="edit-link pointer">click to edit</a>
    <div class="editform" style="display: none;">
      <div class="red">
        Warning: this secret key is public and sent to all members you invite to your group. <br />
        Do not use a sensitive passphrase (like your email or bank account)
      </div>
      <form class="note-form" role="form" action="{% url 'Groups:changeGroupPassword' group.pk %}" method=POST>
        {% csrf_token %}
        <textarea name="form_text" rows="1">{{ group.password }}</textarea>
        <button class="btn btn-primary" type="submit">submit edit</button>
      </form>
    </div>
  </div>

  <div class=box>
    <b>Group membership:</b>
    <br />
      {% if group.openForNewMembers %}
        Membership is <b>OPEN</b>
      {% else %}
        Membership is <b>CLOSED</b>
      {% endif %}
    <br />
    <a pk="{{group.pk}}" class="edit-link pointer">click to edit</a>
    <div class="editform" style="display: none;">
      <form style="margin: 5; padding: 5;" action="{% url 'Groups:changeAcceptingNewMembers' group.pk %}" method="POST">
        {% csrf_token %}
        <span>
          {% if group.openForNewMembers %}
            <input type="radio" name="membership_option" value="open" checked> open &nbsp; &nbsp; &nbsp;
            <input type="radio" name="membership_option" value="closed"> closed &nbsp; &nbsp; &nbsp;
          {% else %}
            <input type="radio" name="membership_option" value="open"> open &nbsp; &nbsp; &nbsp;
            <input type="radio" name="membership_option" value="closed" checked> closed &nbsp; &nbsp; &nbsp;
          {% endif %}
          <button class="btn-sm btn-primary" type="submit">change</button>
        </span>
      </form>
    </div>
  </div>

  <div class=box>
    <b>User permissions:</b>
    <br />
    <a pk="{{group.pk}}" class="edit-link pointer">click to edit</a>
    <div class="editform" style="display: none;">

      {% for admin in admins %}
        <div class="small-box">
          <form style="margin: 5; padding: 5;" action="{% url 'Groups:changePermissions' admin.pk group.pk %}" method="POST">
            {% csrf_token %}
            {{ admin.userprofile.getName }}:
            Administrator
            <span style="float:right">
              <input type="radio" name="permission" value="admin" checked> administrator &nbsp; &nbsp; &nbsp;
              <input type="radio" name="permission" value="moderator"> moderator &nbsp; &nbsp; &nbsp;
              <input type="radio" name="permission" value="member"> member &nbsp; &nbsp; &nbsp;
              <input type="radio" name="permission" value="remove"> remove &nbsp; &nbsp; &nbsp;
              <button class="btn-sm btn-primary" type="submit">change</button>
            </span>
          </form>
        </div>
    {% endfor %}

    {% for moderator in moderators %}
      <div class="small-box">
        <form style="margin: 5; padding: 5;" action="{% url 'Groups:changePermissions' moderator.pk group.pk %}" method="POST">
          {% csrf_token %}
          {{ moderator.userprofile.getName }}:
          Moderator
          <span style="float:right">
            <input type="radio" name="permission" value="admin"> administrator &nbsp; &nbsp; &nbsp;
            <input type="radio" name="permission" value="moderator" checked> moderator &nbsp; &nbsp; &nbsp;
            <input type="radio" name="permission" value="member"> member &nbsp; &nbsp; &nbsp;
            <input type="radio" name="permission" value="remove"> remove &nbsp; &nbsp; &nbsp;
            <button class="btn-sm btn-primary" type="submit">change</button>
          </span>
        </form>
      </div>
  {% endfor %}

  {% for member in members %}
    <div class="small-box">
      <form style="margin: 5; padding: 5;" action="{% url 'Groups:changePermissions' member.pk group.pk %}" method="POST">
        {% csrf_token %}
        {{ member.userprofile.getName }}:
        Member
        <span style="float:right">
          <input type="radio" name="permission" value="admin"> administrator &nbsp; &nbsp; &nbsp;
          <input type="radio" name="permission" value="moderator"> moderator &nbsp; &nbsp; &nbsp;
          <input type="radio" name="permission" value="member" checked> member &nbsp; &nbsp; &nbsp;
          <input type="radio" name="permission" value="remove"> remove &nbsp; &nbsp; &nbsp;
          <button class="btn-sm btn-primary" type="submit">change</button>
        </span>
      </form>
    </div>
  {% endfor %}


    </div>
  </div>

  <div class=box>
    <b>Delete group:</b>
    <div class="red">
      Warning: this is permanent. Group will be removed from all group members.
    </div>
    <a href="{% url 'Groups:deleteGroup' group.pk %}">Click to delete</a>
  </div>

{% endblock %}

mySite/Groups/templates/Groups/groupMemberView.html
{% extends "MCBase/base.html" %}
{% load staticfiles %}
{% load MCBase_templatetags %}

{% block javascript %}
  <link rel="stylesheet" href="{% static 'Groups/css/groupMemberView.css' %}">
  <script src="{% static 'Groups/js/groupMemberInterface.js' %}"></script>
{% endblock %}

{% block title %}
  Groups
{% endblock %}



{% block body_block %}
<div class="box">
  <div id="header">
    <h1>
      {{ group.name }}
    </h1>
    {% if group.description|length != 0 %}
      <div class="group-description">
        {{ group.description}}
      </div>
    {% endif %}
    <a class="btn btn-primary" role="button" href="{% url 'Uploader:uploadInterface' group.pk %}">add new paper</a>
    {% if isAdmin %}
      <a class="btn btn-primary" role="button" href="{% url 'Groups:groupAdminPanel' group.pk %}">administration tools</a>
    {% endif %}
    <a style="float: right;" class="btn btn-danger" role="button" href="{% url 'Groups:removeSelfFromGroup' group.pk %}">remove self from group</a>
  </div>
  <div class="vertical-spacer"></div>
  <hr />
  <div>
    <div id="document-list">
      <div class="vertical-spacer"></div>
      {% if documents %}
        {% for document in documents %}
          <div class="small-box">
            <div class="small-box-header">
              {{ document.get_user_alias }}, {{ document.time|age }}
            </div>
            <a href="{% url 'pdfjs:viewer' document.pk %}">
              {{ document.getTitle }}
            </a>
            {% if document.description|length != 0 %}
            <hr />
            <div class="document-description">
              {{ document.description }}
            </div>
            {% endif %}

            <div class="small-box-footer">
              [<a href="{{ document.docfile.url }}" download>
                download
              </a>]
              &nbsp; &nbsp; &nbsp;
            {% if isModerator or document.user.pk == request.user.pk %}
              [<a href="{% url 'Groups:documentAdminPanel' document.pk %}">
                moderator tools
              </a>]
            {% endif %}
          </div>


          </div>
        {% endfor %}
      {% else %}
        <div class="vertical-spacer"></div>
        <div class="small-box">
          No shared papers in the group. Why don't you try <a href="{% url 'Uploader:uploadInterface' group.pk %}">uploading</a>
          a paper.
        </a>
      {% endif %}
    </div>
  </div>


</div>
{% endblock %}

mySite/Groups/templates/Groups/joinGroupInterface.html
{% extends "MCBase/base.html" %}
{% load staticfiles %}

{% block javascript %}
  <link rel="stylesheet" href="{% static 'Uploader/css/uploadInterface.css' %}">
{% endblock %}

{% block title %}
  join group
{% endblock %}



{% block body_block %}
{% if request.user.is_authenticated %}
  <div class="box">
    <h1><b>{{ group.name }}</b></h1>
    <form action="{% url 'Groups:joinGroup' group.pk %}" method="POST">
      {% csrf_token %}
      <div class="small-box">
          secret key: &nbsp;
          <input type="text" name="password">
          {% if incorrect_password %}
            <span style="color: red;">incorrect password</span>
          {% endif %}
          {% if group_closed %}
            <span style="color: red;">Group is currently closed to new members.</span>
          {% endif %}
      </div>
      <button class="btn btn-primary" type="submit">Submit</button>
    </form>
  </div>
{% else %}
  <h1>
    You must log in with social media before joining.
  </h1>
  <div class="modal-body">

  <div class="row center-text">
    <a class="socialAuthModal-link" href="/login/google-oauth2/?next={% url 'Groups:joinGroupInterface' group.pk %}">
      <img height="150" src="/static/MCBase/images/google-icon.png" alt="Log in with google!">
    </a>
    <a class="socialAuthModal-link" href="/login/facebook/?next={% url 'Groups:joinGroupInterface' group.pk %}">
      <img height="150" src="/static/MCBase/images/facebook-icon.png" alt="Log in with facebook!">
    </a>

    <a class="socialAuthModal-link" href="/login/twitter/?next={% url 'Groups:joinGroupInterface' group.pk %}">
      <img height="150" src="/static/MCBase/images/twitter-icon.png" alt="Log in with twitter!">
    </a>
  </div>

</div>

{% endif %}

{% endblock %}